### ISSUE TITLE
train on CMU-MOSEI

### ISSUE THREAD

**Issue by lxq666666** [Turdidae810/HSCL#2]
你好，train on CMU-MOSEI时出现
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    solver.train_and_eval()
  File "/home/lxq/project/HSCL-main/src/solver.py", line 196, in train_and_eval
    train_main_loss = train(model, optimizer_main, criterion)
  File "/home/lxq/project/HSCL-main/src/solver.py", line 116, in train
    preds,feature,fusion,feature_at,feature_vt = model(text, visual, audio, vlens, alens, bert_sent, bert_sent_type, bert_sent_mask)
  File "/home/lxq/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lxq/project/HSCL-main/src/model.py", line 93, in forward
    visual_based_text = self.tv_encoder(x=text, x_k=visual, x_v=visual,key_padding_mask=mask_v,attn_mask=None)
  File "/home/lxq/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lxq/project/HSCL-main/src/modules/encoders.py", line 231, in forward
    x, _ = self.cross_attn(query=x, key=x_k, value=x_v, key_padding_mask=key_padding_mask)
  File "/home/lxq/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lxq/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 978, in forward
    v_proj_weight=self.v_proj_weight)
  File "/home/lxq/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/nn/functional.py", line 4695, in multi_head_attention_forward
    assert len1 == embed_dim and len2 == key.size(-1)
AssertionError
怎么回事，该怎么办

**Comment by Turdidae810** [comment]
The issue was caused by an error in model.py. I have already updated model.py. You can now try running the updated code.

**Comment by lxq666666** [comment]
thank you

**Comment by lxq666666** [comment]
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    solver.train_and_eval()
  File "/home/wsw/data/lxq/HSCL-main/src/solver.py", line 196, in train_and_eval
    train_main_loss = train(model, optimizer_main, criterion)
  File "/home/wsw/data/lxq/HSCL-main/src/solver.py", line 108, in train
    with torch.cuda.device(0):
  File "/home/wsw/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/cuda/__init__.py", line 223, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
  File "/home/wsw/miniconda3/envs/HSCL/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
配置了torch =1.8.0+cu111为什么还会不能用

**Comment by Turdidae810** [comment]
先确认您的机器上是否有GPU可以使用。如果在有GPU的情况下发生上述错误，可以尝试将 main.py 的第14行修改为 os.environ["CUDA_VISIBLE_DEVICES"] = "0"。注意GPU的编号不能超过GPU总数。

**Comment by lxq666666** [comment]
非常感谢
