### ISSUE TITLE
MOSI

### ISSUE THREAD

**Issue by MrLeeGe** [Turdidae810/HSCL#3]
Traceback (most recent call last):
  File "D:\pycharm\HSCL-main\src\main.py", line 44, in <module>
    train_loader = get_loader(args, train_config, shuffle=True)
  File "D:\pycharm\HSCL-main\src\data_loader.py", line 52, in get_loader
    dataset = MSADataset(config, hp)
  File "D:\pycharm\HSCL-main\src\data_loader.py", line 21, in __init__
    dataset = MOSI(args)
  File "D:\pycharm\HSCL-main\src\create_dataset.py", line 90, in __init__
    label = np.concatenate((train_split_noalign['labels'],dev_split_noalign['labels'], test_split_noalign['labels']),axis=0)
KeyError: 'labels'

Process finished with exit code 1
你好，我并没有修改你的预处理代码，这个问题是怎么造成的呢

**Comment by Turdidae810** [comment]
请问您的数据集是否是从指定链接下载的？本工作使用了和 MMIM 相同的数据集。

**Comment by MrLeeGe** [comment]
您好，我重新下载了数据集，已经解决了问题，感谢你的回复
